/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : ProductId, 'quantity' : bigint }
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'slug' : string,
  'description' : string,
  'imageUrl' : string,
}
export type CategoryId = string;
export interface Product {
  'id' : ProductId,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'stock' : bigint,
  'isFeatured' : boolean,
  'materials' : Array<string>,
  'category' : CategoryId,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
  'isBestSeller' : boolean,
}
export type ProductId = string;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WishlistItem { 'productId' : ProductId }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'addToWishlist' : ActorMethod<[WishlistItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCategory' : ActorMethod<[Category], undefined>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBestSellers' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<WishlistItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'removeFromWishlist' : ActorMethod<[ProductId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartQuantity' : ActorMethod<[ProductId, bigint], undefined>,
  'updateCategory' : ActorMethod<[CategoryId, Category], undefined>,
  'updateProduct' : ActorMethod<[ProductId, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];